### PR TITLE
Documentation improvement for runtime

### LINKED ISSUE #304: deny missing docs on public items
Right now we actually have a lot of `//` comments that are intended to be `///` doc comments. This is rampant throughout our pallets. A really good way to fix this would be to enforce `#[deny(missing_docs)]` at the crate level for each of our crates and then work through all the compile errors. Prob a big effort but will dramatically improve @rajkaramchedu's effort to improve the subtensor docs, and will require us to document things going forward as we create them.

AC:
- [ ] add `#[deny(missing_docs)]` to all subtensor crates
- [ ] fix the resulting compile errors, upgrading any `//` item-level comments to `///` and ensuring they do not introduce any broken doc links
- [ ] `cargo doc --workspace` passing without any broken doc links

### PR DESCRIPTION
**Pull request by open-junius**
## Description
The pr add all missed doc for all crates. make sure the compilation is successful with the check of #[deny(missing_docs)]

## Related Issue(s)

- Closes #304 

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update
- [ ] Other (please describe):

## Breaking Change
No
## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have run `cargo fmt` and `cargo clippy` to ensure my code is formatted and linted correctly
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots (if applicable)

Please include any relevant screenshots or GIFs that demonstrate the changes made.

## Additional Notes
The pr will fix #304

### CODE REVIEW

File: pallets/admin-utils/src/lib.rs [hunk 1]
```diff
@@ -65,11 +72,12 @@ pub mod pallet {
         MaxAllowedUIdsNotAllowed,
     }
 
-    // Dispatchable functions allows users to interact with the pallet and invoke state changes.
-    // These functions materialize as "extrinsics", which are often compared to transactions.
-    // Dispatchable functions must be annotated with a weight and must return a DispatchResult.
+    /// Dispatchable functions allows users to interact with the pallet and invoke state changes.
     #[pallet::call]
     impl<T: Config> Pallet<T> {
+        /// The extrinsic set the new authorities for Aura consensus.
```
Comment (camfairchild) [inline pallets/admin-utils/src/lib.rs]:
```suggestion
        /// The extrinsic sets the new authorities for Aura consensus.
```

File: pallets/admin-utils/src/lib.rs [hunk 2]
```diff
@@ -759,6 +869,9 @@ pub mod pallet {
             Ok(())
         }
 
+        /// The extrinsic sets the recycled RAO for a subnet.
+        /// It is only callable by the root account.
+        /// The extrinsic will call the Subtensor pallet to set the recycled RAO.
```
Comment (camfairchild) [inline pallets/admin-utils/src/lib.rs]: Please correct to the below call

File: pallets/admin-utils/src/lib.rs [hunk 3]
```diff
@@ -788,6 +902,9 @@ pub mod pallet {
             Ok(())
         }
 
+        /// The extrinsic sets the maximum stake required for nominators.
+        /// It is only callable by the root account.
+        /// The extrinsic will call the Subtensor pallet to set the maximum stake required for nominators.
```
Comment (camfairchild) [inline pallets/admin-utils/src/lib.rs]: Please correct for the below call

File: pallets/subtensor/src/lib.rs [hunk 4]
```diff
@@ -207,50 +253,61 @@ pub mod pallet {
...
         StorageValue<_, u64, ValueQuery, DefaultSenateRequiredStakePercentage<T>>;
 
-    // ============================
-    // ==== Staking + Accounts ====
-    // ============================
+    /// ============================
+    /// ==== Staking + Accounts ====
+    /// ============================
+    /// Total Rao in circulation.
     #[pallet::type_value]
```
Comment (orriin) [inline pallets/subtensor/src/lib.rs]:
```suggestion
    // ============================
    // ==== Staking + Accounts ====
    // ============================
    
    /// Total Rao in circulation.
    #[pallet::type_value]
```

File: pallets/subtensor/src/lib.rs [hunk 5]
```diff
@@ -307,45 +364,55 @@ pub mod pallet {
         DefaultAccountTake<T>,
     >;
 
-    // =====================================
-    // ==== Difficulty / Registrations =====
-    // =====================================
+    /// =====================================
+    /// ==== Difficulty / Registrations =====
+    /// =====================================
+    /// Default last adjustment block.
```
Comment (orriin) [inline pallets/subtensor/src/lib.rs]:
```suggestion
    /// =====================================
    
    /// Default last adjustment block.
```

File: pallets/admin-utils/src/lib.rs [hunk 6]
```diff
@@ -258,6 +293,9 @@ pub mod pallet {
             Ok(())
         }
 
+        /// The extrinsic sets the adjustment beta for a subnet.
+        /// It is only callable by the root account.
+        /// The extrinsic will call the Subtensor pallet to set the adjustment beta.
```
Comment (camfairchild) [inline pallets/admin-utils/src/lib.rs]: please correct for the below call

File: pallets/subtensor/src/lib.rs [hunk 7]
```diff
@@ -380,69 +447,85 @@ pub mod pallet {
     pub type RAORecycledForRegistration<T> =
         StorageMap<_, Identity, u16, u64, ValueQuery, DefaultRAORecycledForRegistration<T>>;
 
-    // ==============================
-    // ==== Subnetworks Storage =====
-    // ==============================
+    /// ==============================
+    /// ==== Subnetworks Storage =====
+    /// ==============================
+    /// Default number of networks.
```
Comment (orriin) [inline pallets/subtensor/src/lib.rs]:
```suggestion
    /// ==============================
   
    /// Default number of networks.
```

File: pallets/subtensor/src/lib.rs [hunk 8]
```diff
@@ -508,34 +591,41 @@ pub mod pallet {
     pub type NominatorMinRequiredStake<T> =
         StorageValue<_, u64, ValueQuery, DefaultNominatorMinRequiredStake<T>>;
 
-    // ==============================
-    // ==== Subnetwork Features =====
-    // ==============================
+    /// ==============================
+    /// ==== Subnetwork Features =====
+    /// ==============================
+    /// Default value for emission values.
```
Comment (orriin) [inline pallets/subtensor/src/lib.rs]:
```suggestion
    /// ==============================
    
    /// Default value for emission values.
```

File: pallets/subtensor/src/lib.rs [hunk 9]
```diff
@@ -640,77 +748,95 @@ pub mod pallet {
         OptionQuery,
     >;
 
-    // =======================================
-    // ==== Subnetwork Hyperparam storage ====
-    // =======================================
+    /// =======================================
+    /// ==== Subnetwork Hyperparam storage ====
+    /// =======================================
+    /// Default weights set rate limit.
```
Comment (orriin) [inline pallets/subtensor/src/lib.rs]:
```suggestion
    /// =======================================
    
    /// Default weights set rate limit.
```

File: pallets/subtensor/src/lib.rs [hunk 10]
```diff
@@ -786,29 +912,35 @@ pub mod pallet {
     pub type AdjustmentAlpha<T: Config> =
         StorageMap<_, Identity, u16, u64, ValueQuery, DefaultAdjustmentAlpha<T>>;
 
-    // =======================================
-    // ==== Subnetwork Consensus Storage  ====
-    // =======================================
+    /// =======================================
+    /// ==== Subnetwork Consensus Storage  ====
+    /// =======================================
+    /// Value definition for vector of u16.
```
Comment (orriin) [inline pallets/subtensor/src/lib.rs]:
```suggestion
    /// =======================================
    
    /// Value definition for vector of u16.
```

File: pallets/subtensor/src/lib.rs [hunk 11]
```diff
@@ -1344,36 +1476,36 @@ pub mod pallet {
...
+        /// * 'take' (u16):
+        /// 	- The new stake proportion that this hotkey takes from delegations.
+        ///        The new value can be between 0 and 11_796 and should be strictly
+        ///        greater than the previous value. It T is the new value (rational number),
+        ///        the the parameter is calculated as [65535 * T]. For example, 1% would be
+        ///        [0.01 * 65535] = [655.35] = 655
+        ///
+        /// # Event:
+        /// * TakeDecreased;
+        /// 	- On successfully setting a decreased take for this hotkey.
```
Comment (orriin) [inline pallets/subtensor/src/lib.rs]: do you mean
```suggestion
        /// * TakeIncreased;
        /// 	- On successfully setting a increased take for this hotkey.
```

File: pallets/subtensor/src/lib.rs [hunk 12]
```diff
@@ -1344,36 +1476,36 @@ pub mod pallet {
...
+        /// * 'origin': (<T as frame_system::Config>::Origin):
+        /// 	- The signature of the caller's coldkey.
+        ///
+        /// * 'hotkey' (T::AccountId):
+        /// 	- The hotkey we are delegating (must be owned by the coldkey.)
+        ///
+        /// * 'take' (u16):
+        /// 	- The new stake proportion that this hotkey takes from delegations.
+        ///        The new value can be between 0 and 11_796 and should be strictly
+        ///        greater than the previous value. It T is the new value (rational number),
```
Comment (orriin) [inline pallets/subtensor/src/lib.rs]:
```suggestion
        ///        greater than the previous value. T is the new value (rational number),
```

File: pallets/subtensor/src/lib.rs [hunk 13]
```diff
@@ -1344,36 +1476,36 @@ pub mod pallet {
...
+        ///
+        /// # Raises:
+        /// * 'NotRegistered':
+        /// 	- The hotkey we are delegating is not registered on the network.
+        ///
+        /// * 'NonAssociatedColdKey':
+        /// 	- The hotkey we are delegating is not owned by the calling coldkey.
+        ///
+        /// * 'InvalidTake':
+        /// 	- The delegate is setting a take which is not lower than the previous.
```
Comment (orriin) [inline pallets/subtensor/src/lib.rs]:
```suggestion
        /// 	- The delegate is setting a take which is not greater than the previous.
```

File: pallets/admin-utils/src/lib.rs [hunk 14]
```diff
@@ -104,6 +118,9 @@ pub mod pallet {
             Ok(())
         }
 
+        /// The extrinsic sets the serving rate limit for a subnet.
+        /// It is only callable by the root account.
```
Comment (camfairchild) [inline pallets/admin-utils/src/lib.rs]: Please fix this line for each call that allows the subnet owner OR the root account

File: pallets/subtensor/src/lib.rs [hunk 15]
```diff
@@ -1430,38 +1561,37 @@ pub mod pallet {
...
-        // 		- Thrown if the coldkey does not own the hotkey we are unstaking from.
-        //
-        // 	* 'NotEnoughStaketoWithdraw':
-        // 		- Thrown if there is not enough stake on the hotkey to withdwraw this amount.
-        //
-        // 	* 'CouldNotConvertToBalance':
-        // 		- Thrown if we could not convert this amount to a balance.
-        //
-        //
+        /// ---- Remove stake from the staking account. The call must be made
```
Comment (orriin) [inline pallets/subtensor/src/lib.rs]:
```suggestion
        /// Remove stake from the staking account. The call must be made
```

File: pallets/subtensor/src/lib.rs [hunk 16]
```diff
@@ -1782,7 +1942,7 @@ pub mod pallet {
 
     // ---- Subtensor helper functions.
     impl<T: Config> Pallet<T> {
-        // --- Returns the transaction priority for setting weights.
+        /// --- Returns the transaction priority for setting weights.
```
Comment (orriin) [inline pallets/subtensor/src/lib.rs]:
```suggestion
        /// Returns the transaction priority for setting weights.
```

File: pallets/subtensor/src/lib.rs [hunk 17]
```diff
@@ -1794,12 +1954,13 @@ pub mod pallet {
             0
         }
 
-        // --- Is the caller allowed to set weights
+        /// --- Is the caller allowed to set weights
```
Comment (orriin) [inline pallets/subtensor/src/lib.rs]:
```suggestion
        /// Is the caller allowed to set weights
```

File: pallets/admin-utils/src/lib.rs [hunk 18]
```diff
@@ -654,6 +746,9 @@ pub mod pallet {
             Ok(())
         }
 
+        /// The extrinsic sets the network lock for the network.
+        /// It is only callable by the root account.
+        /// The extrinsic will call the Subtensor pallet to set the network lock.
```
Comment (camfairchild) [inline pallets/admin-utils/src/lib.rs]: Please correct for the below call

File: pallets/subtensor/src/serving.rs [hunk 19]
```diff
@@ -86,7 +86,7 @@ impl<T: Config> Pallet<T> {
             Error::<T>::ServingRateLimitExceeded
         );
 
-        // --- 6. We insert the axon meta.
+        // --- 5. We insert the axon meta.
```
Comment (orriin) [inline pallets/subtensor/src/serving.rs]: I think we should remove these numbers, they're a pain to maintain

**Review by orriin — APPROVED** [review]

File: pallets/admin-utils/src/lib.rs [hunk 20]
```diff
@@ -667,6 +762,9 @@ pub mod pallet {
...
```
Comment (camfairchild) [inline pallets/admin-utils/src/lib.rs]: Please correct for the below call

File: pallets/admin-utils/src/lib.rs [hunk 21]
```diff
@@ -687,6 +785,9 @@ pub mod pallet {
...
```
Comment (camfairchild) [inline pallets/admin-utils/src/lib.rs]:
```suggestion
        /// The extrinsic sets the minimum network lock cost for the network.
        /// It is only callable by the root account.
        /// The extrinsic will call the Subtensor pallet to set the minimum network lock cost.
```

File: pallets/subtensor/src/lib.rs [hunk 22]
```diff
@@ -57,6 +57,7 @@ pub mod subnet_info;
 extern crate alloc;
 pub mod migration;
 
+#[deny(missing_docs)]
```
Comment (keithtensor) [inline pallets/subtensor/src/lib.rs:60]: We should just do a crate-wide deny by using `#![deny(missing_docs)]`

**Review by camfairchild — CHANGES_REQUESTED** [review]
Partial review. Needs some changes in the first file.

File: pallets/admin-utils/src/lib.rs [hunk 23]
```diff
@@ -624,6 +710,9 @@ pub mod pallet {
             Ok(())
         }
 
+        /// The extrinsic sets the network rate limit for the network.
+        /// It is only callable by the root account.
+        /// The extrinsic will call the Subtensor pallet to set the network rate limit.
```
Comment (rajkaramchedu) [inline pallets/admin-utils/src/lib.rs:715]: Some docstrings say "for the network" and others "for the subnet". We should clarify how "for the network" differs from "for the subnet", and also clarify "for the network" if root account still synonymous with the subnet owner?

File: pallets/admin-utils/src/lib.rs [hunk 24]
```diff
@@ -209,6 +238,9 @@ pub mod pallet {
             Ok(())
         }
 
+        /// The extrinsic sets the adjustment interval for a subnet.
+        /// It is only callable by the root account.
```
Comment (rajkaramchedu) [inline pallets/admin-utils/src/lib.rs]: We currently say in our docs that this hyperparam must not be changed. Should the doc be revised to say a subnet owner can now change this param? See https://github.com/opentensor/bittensor/blob/staging/bittensor/commands/network.py#L307 (only changeable hyperparams are in this list, should we update this list?) cc: @garrett-opentensor

File: pallets/admin-utils/src/lib.rs (hunk 23 above)
Comment (open-junius) [reply pallets/admin-utils/src/lib.rs:715]: how about we use "for the network" if there is no netuid in the parameter. and "for the subnet" with specific netuid.

File: pallets/subtensor/src/lib.rs (hunk 22 above)
Comment (open-junius) [reply pallets/subtensor/src/lib.rs:60]: it will check all functions and structs. we can create new issues and PRs for these. make easier for review.

File: pallets/admin-utils/src/lib.rs (hunk 24 above)
Comment (camfairchild) [reply pallets/admin-utils/src/lib.rs]: > Should the doc be revised to say a subnet owner can now change this param.  

The doc is correct. This is only changeable by the root account (i.e. `sudo`/`triumvirate`, etc.)

File: pallets/admin-utils/src/lib.rs (hunk 23 above)
Comment (rajkaramchedu) [reply pallets/admin-utils/src/lib.rs:715]: But first, what does "for the network" mean here? What is it referring to? Normally these things refer to subnets but I guess that's not it? I am not getting the meaning of "network rate limit for the network" here. Also it now says "callable by the root account"... I am not getting this either. Root account is doing what here? When we know that, we can tweak the wording then.

File: pallets/admin-utils/src/lib.rs (hunk 24 above)
Comment (rajkaramchedu) [reply pallets/admin-utils/src/lib.rs]: > > Should the doc be revised to say a subnet owner can now change this param.
> 
> The doc is correct. This is only changeable by the root account (i.e. `sudo`/`triumvirate`, etc.)

I guess I should be clearer. All hyperparams that are editable by a subnet owner do already require, by default, "sudo" (it says in the key, value pairs in the above network.py loc link). My question is, the current list does not contain the "adjustment interval" hyperparam, and hence my docs also do not have it, so should I now add this "adjustment interval" to the docs, is my question. By implication, if I do add it to the docs, then I would think someone in @garrett-opentensor's team should also add it to the list in the above network.py code.

Comment (camfairchild) [reply pallets/admin-utils/src/lib.rs]: > > > Should the doc be revised to say a subnet owner can now change this param.
> > 
> > 
> > The doc is correct. This is only changeable by the root account (i.e. `sudo`/`triumvirate`, etc.)
> 
> All hyperparams that are editable by a subnet owner do already require, by default, "sudo" 

This is not true. These params (the ones changeable by the subnet owner) are changeable by either of `sudo` ("root") or subnet owner. However, this specific one is only changeable by `sudo` (i.e. not `subnetOwner`)

I think adding it to the docs would be good, however, note that it is not changeable by the subnet owner.


edit: root is *not* equivalent to subnetOwner ("SN admin")

**Review by sam0x17 — APPROVED** [review]
looks good once any pending tweaks are added 👍🏻

File: pallets/admin-utils/src/lib.rs (hunk 23 above)
Comment (open-junius) [reply pallets/admin-utils/src/lib.rs:715]: the network is subtensor blockchain in the context. I think subnet is separate network, they are connected by its own connection method. but sutnet's validators are also playing important role in subtensor blockchain. 
I think we need the terminology for our blockchain, the whole system including chain and all subnets.
The root account is a special account in substrate based chain, it can call any function and we can set the different privilege for normal account and root account. At the beginning of blockchain launch, it is a special real account. Later, it is from governance.

Comment (sam0x17) [reply pallets/admin-utils/src/lib.rs:715]: yeah, often "network" is used to refer to the entire blockchain network collectively, so "all of finney" for example
