### PR TITLE
Fix/childkey emission distribution

### LINKED ISSUE #855: Hotkey draining issues
1. Childkey take gets added to `PendingdHotkeyEmission` in `accumulate_hotkey_emission` and then is distributed among nominators in `drain_hotkey_emission`.
2. Miner emission is also subject to distribution to nominators in `drain_hotkey_emission` because it is added to `PendingdHotkeyEmission`.
3. When childkey take is calculated in `accumulate_hotkey_emission`, it is calculated off the total childkey pending emission, even if some portion of it comes not from parent, but from nominators.

### PR DESCRIPTION
**Pull request by gztensor**
## Description
Fixes hotkey draining issues:
1. Miner emission should not be distributed to nominators
2. Childkey take should not be distributed to nominators

## Related Issue(s)

- Closes #855 

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please describe):

## Breaking Change

n/a

## Checklist
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have run `cargo fmt` and `cargo clippy` to ensure my code is formatted and linted correctly
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by sam0x17 — DISMISSED** [review]

File: pallets/subtensor/src/coinbase/run_coinbase.rs [hunk 1]
```diff
@@ -199,59 +199,73 @@ impl<T: Config> Pallet<T> {
...
-        let take_proportion: I64F64 = I64F64::from_num(Self::get_childkey_take(hotkey, netuid))
-            .saturating_div(I64F64::from_num(u16::MAX));
-        let hotkey_take: u64 = take_proportion
-            .saturating_mul(I64F64::from_num(validating_emission))
-            .to_num::<u64>();
-        // NOTE: Only the validation emission should be split amongst parents.
-
-        // --- 2. Compute the remaining emission after the hotkey's share is deducted.
-        let emission_minus_take: u64 = validating_emission.saturating_sub(hotkey_take);
+        let childkey_take_proportion: I64F64 =
```
Comment (camfairchild) [inline pallets/subtensor/src/coinbase/run_coinbase.rs]: This precision differs from the later use when multiplying on 233

**Review by camfairchild — CHANGES_REQUESTED** [review]

File: pallets/subtensor/src/coinbase/run_coinbase.rs (hunk 1 above)
Comment (gztensor) [reply pallets/subtensor/src/coinbase/run_coinbase.rs]: `childkey_take_proportion` value is between 0 and 1, and we're multiplying u64 parent_emission by this value. Looks ok to me. Is there anything wrong there?

File: pallets/subtensor/src/coinbase/run_coinbase.rs [hunk 2]
```diff
@@ -199,59 +199,73 @@ impl<T: Config> Pallet<T> {
...
                 let stake_from_parent: I96F32 = I96F32::from_num(parent_stake).saturating_mul(
                     I96F32::from_num(proportion).saturating_div(I96F32::from_num(u64::MAX)),
                 );
                 let proportion_from_parent: I96F32 =
                     stake_from_parent.saturating_div(I96F32::from_num(total_hotkey_stake));
-                let parent_emission_take: u64 = proportion_from_parent
-                    .saturating_mul(I96F32::from_num(emission_minus_take))
+                let parent_emission: u64 = proportion_from_parent
+                    .saturating_mul(I96F32::from_num(validating_emission))
+                    .to_num::<u64>();
```
Comment (camfairchild) [inline pallets/subtensor/src/coinbase/run_coinbase.rs]: probably shouldn't cast here (keep as a float). Maybe only cast the final results.

**Review by camfairchild — DISMISSED** [review]
approved with a nit

**Review by camfairchild — DISMISSED** [review]

**Review by sam0x17 — APPROVED** [review]

File: pallets/subtensor/tests/children.rs [hunk 3]
```diff
@@ -3428,3 +3428,277 @@ fn test_set_weights_no_parent() {
...
+        // Run run_coinbase until PendingHotkeyEmission are populated
+        while pallet_subtensor::PendingdHotkeyEmission::<Test>::get(child) == 0 {
+            step_block(1);
+        }
+
+        // Prevent further subnet epochs
+        pallet_subtensor::Tempo::<Test>::set(netuid, u16::MAX);
+        pallet_subtensor::Tempo::<Test>::set(root_id, u16::MAX);
+
+        // Run run_coinbase until PendingHotkeyEmission is drained for both child and parent
```
Comment (camfairchild) [inline pallets/subtensor/tests/children.rs:3541]: Nit: Why not just populate pendinghotkeyemission directly.

**Review by camfairchild — APPROVED** [review]
