### PR TITLE
Fix Senate membership changes

### LINKED ISSUE #430: Fix Senate Membership
### Describe the bug

The Senate is comprised of the top peers by Stake in the root subnet (SN0). This group is a governance group that is permitted to vote on proposals made by the Triumvirate. 

The issue is that the Senate membership is never update outside of initially adding a key (and swapping, if applicable) to the subnet during the root registration call. This means that when a peer registers for the root subnet they are given a status of either Senate membership, and if their relative Stake changes above or below the threshold to join/leave the Senate, their membership is not updated.

### To Reproduce

1. Register in the root subnet with low Stake, but enough to register (i.e. lowest_peer.stake + \epsilon)
2. Notice you are not in the Senate
3. Add sufficient Stake to qualify for the Senate
4. Notice you are still not in the Senate

### Expected behavior

I would expect the membership status to change automatically or for a call to change it to reflect the Stake holdings of the root subnet peers.

### Screenshots

_No response_

### Environment

OS: NA, Runtime Version: 148

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by camfairchild**
Devnet companion: #557

## Description

See related issue. This PR fixes a bug where current root members cannot become a Senate member after attaining the requirements *after* registering on the root network, initially.

This PR adds the call `subtensorModule.adjust_senate(hotkey)` to attempt to join the Senate when eligible.

## Related Issue(s)

- Closes #430 

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please describe):

## TODO
- [ ] Benchmarking weights

## Breaking Change
NA

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have run `cargo fmt` and `cargo clippy` to ensure my code is formatted and linted correctly
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshots (if applicable)

NA

## Additional Notes

An alternative solution is to call `join_senate_if_eligible` during a `root_register` call if the hotkey is already registered

### CODE REVIEW

**Review by sam0x17 — DISMISSED** [review]

File: pallets/subtensor/src/lib.rs [hunk 1]
```diff
@@ -1903,6 +1903,15 @@ pub mod pallet {
             Self::do_root_register(origin, hotkey)
         }
 
+        /// Attempt to adjust the senate membership to include a hotkey
+        #[pallet::call_index(63)]
+        #[pallet::weight((Weight::from_parts(0, 0)
+		.saturating_add(T::DbWeight::get().reads(0))
+		.saturating_add(T::DbWeight::get().writes(0)), DispatchClass::Normal, Pays::No))]
```
Comment (open-junius) [inline pallets/subtensor/src/lib.rs]: Pay::No is fine for call from sudo. But the extrinsic can be called by any coldkey. The use may attach the chain by sending too many extrinsics.

Comment (camfairchild) [reply pallets/subtensor/src/lib.rs]: I think this could be a pays::yes
```suggestion
		.saturating_add(T::DbWeight::get().writes(0)), DispatchClass::Normal, Pays::Yes))]
```

**Review by sam0x17 — APPROVED** [review]

File: pallets/subtensor/src/lib.rs (hunk 1 above)
Comment (open-junius) [reply pallets/subtensor/src/lib.rs]: Not sure if the weights will be auto calculated later. At lease, the basic extrinsic fee will be charged if Pays::Yes.

**Review by open-junius — APPROVED** [review]

**Review by distributedstatemachine — APPROVED** [review]

**Review by sam0x17 — APPROVED** [review]

**Comment by sam0x17** [comment]
clippy
