### PR TITLE
Fix doc for storage

### LINKED ISSUE #2099: Incorrect placement of Rustdoc comments on storage variables
**A LOT** of Rustdoc comments on storage variables have incorrect positioning which means external tooling that read the node's metadata has no access to these comments. 

Here's a real example straight from the codebase:

```rust
// ❌ Example of incorrect Rustdoc
#[pallet::storage] // --- MAP ( netuid ) --> alpha_supply_user_in_pool | Returns the amount of alpha in the pool provided by users as liquidity.
pub type SubnetAlphaInProvided<T: Config> =
    StorageMap<_, Identity, NetUid, AlphaCurrency, ValueQuery, DefaultZeroAlpha<T>>;

// ✅ Example of correct Rustdoc
#[pallet::storage]
/// --- MAP ( netuid ) --> alpha_supply_in_subnet | Returns the amount of alpha in the subnet.
pub type SubnetAlphaOut<T: Config> =
    StorageMap<_, Identity, NetUid, AlphaCurrency, ValueQuery, DefaultZeroAlpha<T>>;
```

Why it matters? Because correctly placed Rustdoc comments greatly improve the DX of working with Bittensor. Here's an example how the above storage variables look like after types generation in TypeScript:

Image

### PR DESCRIPTION
**Pull request by open-junius**
## Description
The pr improves the doc for storage definition in subtensor pallet.

## Related Issue(s)

- Closes #2099 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please describe):

## Breaking Change

If this PR introduces a breaking change, please provide a detailed description of the impact and the migration path for existing applications.

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have run `cargo fmt` and `cargo clippy` to ensure my code is formatted and linted correctly
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots (if applicable)

Please include any relevant screenshots or GIFs that demonstrate the changes made.

## Additional Notes

Please provide any additional information or context that may be helpful for reviewers.

### CODE REVIEW

File: pallets/subtensor/src/lib.rs [hunk 1]
```diff
@@ -313,103 +313,116 @@ pub mod pallet {
...
     pub fn TotalSupply<T: Config>() -> u64 {
         21_000_000_000_000_000
     }
-    #[pallet::type_value]
+
     /// Default Delegate Take.
+    #[pallet::type_value]
     pub fn DefaultDelegateTake<T: Config>() -> u16 {
         T::InitialDefaultDelegateTake::get()
     }
```
Comment (lorismoulin) [inline pallets/subtensor/src/lib.rs:431]: This file needs a cleanup because this makes no sense to wrap the `#[pallet::constant]` into a type value, we can just use it like that, `type_value` derives a `Get<T>` implementation that is already existing for `InitialDefaultDelegateTake`

Also, a lot of these type values are not used anywhere

edit: I added this to the #2047 issue

**Review by l0r1s — DISMISSED** [review]

File: pallets/subtensor/src/lib.rs (hunk 1 above)
Comment (open-junius) [reply pallets/subtensor/src/lib.rs:431]: I assigned the #2047 to me. Let's merge the PR at first, then we have correct doc for rust doc and type script. I will create a new PR for 2047.

**Review by sam0x17 — DISMISSED** [review]

**Comment by sam0x17** [comment]
merge conflict @juniuszhou

**Review by shamil-gadelshin — DISMISSED** [review]

**Review by l0r1s — DISMISSED** [review]

**Review by sam0x17 — APPROVED** [review]
